version: '3.8'
services:
  app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/test
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db_container
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: